### PR TITLE
Fix warning about comparison unsigned < 0

### LINKED ISSUE #645: Vector Warning: Comparison Unsigned with Zero
Compiling the tests of the current `develop` 8e206bdad75da2704bdac7060a61115a97304df2 with
- nvcc 8.0
- gcc 4.9.2

leads to the following warning in [`ViewSubViewTest.cpp` (L287)](https://github.com/ComputationalRadiationPhysics/alpaka/blob/3dbf4820fb8b4b2c7af534f62448d8362c98c77c/test/unit/mem/view/src//ViewSubViewTest.cpp#L287) (also seen in `src/alpaka/test/unit/mem/buf/src/BufTest.cpp(109)`)
```
include/alpaka/vec/Vec.hpp(346): warning: pointless comparison of unsigned integer with zero
```

first lines of output:
```
/home/huebl/src/alpaka/include/alpaka/vec/Vec.hpp(346): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "auto alpaka::vec::Vec<TDim, TVal>::operator[](TIdx) const->TVal [with TDim=alpaka::dim::DimInt<0UL>, TVal=int64_t, TIdx=std::size_t, <unnamed>=void]" 
(1121): here
            instantiation of "auto alpaka::vec::detail::CreateConcat<Tidx>::create(const alpaka::vec::Vec<TDimL, TVal> &, const alpaka::vec::Vec<TDimR, TVal> &)->TVal [with Tidx=0UL, TDimL=alpaka::dim::DimInt<0UL>, TDimR=alpaka::dim::DimInt<1UL>, TVal=int64_t]" 
(210): here
            instantiation of "auto alpaka::vec::Vec<TDim, TVal>::createVecFromIndexedFnArbitrary<TTFnObj,TArgs...,TIdxSize,TIndices...>(const alpaka::meta::IntegerSequence<TIdxSize, TIndices...> &, TArgs &&...)->alpaka::vec::Vec<TDim, TVal> [with TDim=alpaka::dim::DimInt<1UL>, TVal=int64_t, TTFnObj=alpaka::vec::detail::CreateConcat, TArgs=<const alpaka::vec::Vec<alpaka::dim::DimInt<0UL>, int64_t> &, const alpaka::vec::Vec<alpaka::dim::DimInt<1UL>, int64_t> &>, TIdxSize=std::size_t, TIndices=<0UL>]" 
(227): here
            instantiation of "auto alpaka::vec::Vec<TDim, TVal>::createVecFromIndexedFn<TTFnObj,TArgs...>(TArgs &&...)->alpaka::vec::Vec<TDim, TVal> [with TDim=alpaka::dim::DimInt<1UL>, TVal=int64_t, TTFnObj=alpaka::vec::detail::CreateConcat, TArgs=<const alpaka::vec::Vec<alpaka::dim::DimInt<0UL>, int64_t> &, const alpaka::vec::Vec<alpaka::dim::DimInt<1UL>, int64_t> &>]" 
(523): here
            instantiation of "auto alpaka::vec::createVecFromIndexedFnWorkaround<TDim,TVal,TTFnObj,TArgs...>(TArgs &&...)->alpaka::vec::Vec<TDim, TVal> [with TDim=alpaka::dim::DimInt<1UL>, TVal=int64_t, TTFnObj=alpaka::vec::detail::CreateConcat, TArgs=<const alpaka::vec::Vec<alpaka::dim::DimInt<0UL>, int64_t> &, const alpaka::vec::Vec<alpaka::dim::DimInt<1UL>, int64_t> &>]" 
(1149): here
            [ 19 instantiation contexts not shown ]
```

and last lines:
```
/opt/pkg/devel/boost/1.62.0/gnu/4.9.2/64/opt/include/boost/mpl/for_each.hpp(105): here
            instantiation of "void boost::mpl::for_each(F, Sequence *, TransformOp *) [with Sequence=alpaka::test::acc::TestAccs, TransformOp=boost::mpl::make_identity<mpl_::_>, F=boost::unit_test::ut_detail::generate_test_case_4_type<boost::unit_test::ut_detail::template_test_case_gen<memView::viewSubViewNoOffsetTest_invoker, alpaka::test::acc::TestAccs>, memView::viewSubViewNoOffsetTest_invoker>]" 
/opt/pkg/devel/boost/1.62.0/gnu/4.9.2/64/opt/include/boost/test/tree/test_case_template.hpp(120): here
            instantiation of "boost::unit_test::ut_detail::template_test_case_gen<TestCaseTemplate, TestTypesList>::template_test_case_gen(boost::unit_test::const_string, boost::unit_test::const_string, std::size_t) [with TestCaseTemplate=memView::viewSubViewNoOffsetTest_invoker, TestTypesList=alpaka::test::acc::TestAccs]" 
/home/huebl/src/alpaka/test/unit/mem/view/src//ViewSubViewTest.cpp(287): here
```

in [an assert](https://github.com/ComputationalRadiationPhysics/alpaka/blob/3dbf4820fb8b4b2c7af534f62448d8362c98c77c/include/alpaka/vec/Vec.hpp#L346).

### PR DESCRIPTION
**Pull request by BenjaminW3**
Possibly fixes #645.

@ax3l Please verify if this helps for you.

### CODE REVIEW

File: include/alpaka/core/Assert.hpp [hunk 1]
```diff
@@ -89,5 +89,70 @@ namespace alpaka
...
+                typename TLhs,
+                typename TRhs>
+            struct AssertGreaterThan<
+                TLhs,
+                TRhs,
+                typename std::enable_if<std::is_unsigned<TRhs>::value && (TLhs::value == 0u)>::type>
+            {
+                ALPAKA_NO_HOST_ACC_WARNING
+                ALPAKA_FN_HOST_ACC static auto assertGreaterThan(
+                    TRhs const & lhs)
```
Comment (ax3l) [inline include/alpaka/core/Assert.hpp]: you can also just remove the `lhs` here instead of using `alpaka::ignore_unused`
