### PR TITLE
Fix matMul test compilation for nvcc

### LINKED ISSUE #446: compilation problem in the integration test matMul
I have this compilation problem with the matMul example:

####################################################################

[ 80%] Building NVCC (Device) object matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o
/home/ivan/Desktop/Alpaka_git/alpaka/test/integ/matMul/src//main.cpp(297) (col. 15): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/il_to_str.c", line 7191

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00003f69_00000000-5_main.cpp4.ii".
Compilation aborted.
Aborted (core dumped)
CMake Error at matMul_generated_main.cpp.o.cmake:282 (message):
  Error generating file
  /home/ivan/Desktop/Alpaka_git/alpaka/test/integ/build/matMul/CMakeFiles/matMul.dir/src/./matMul_generated_main.cpp.o

matMul/CMakeFiles/matMul.dir/build.make:63: recipe for target 'matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o' failed
make[2]: *** [matMul/CMakeFiles/matMul.dir/src/matMul_generated_main.cpp.o] Error 1
CMakeFiles/Makefile2:332: recipe for target 'matMul/CMakeFiles/matMul.dir/all' failed
make[1]: *** [matMul/CMakeFiles/matMul.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

#####################################################################

thanks in advance for any help!

### PR DESCRIPTION
**Pull request by BenjaminW3**
Fixes #446

### CODE REVIEW

**Comment by BenjaminW3** [comment]
ready to be merged!

**Comment by BenjaminW3** [comment]
@psychocoderHPC I have merged this trivial test fix without waiting for the review to fix the user issue.
We might want to report this nvcc compiler bug to NVIDIA. However, I can not create a minimal reproducing example because I have no native CUDA installation available at the moment.

File: test/integ/matMul/src/main.cpp [hunk 1]
```diff
@@ -295,7 +296,7 @@ struct MatMulTester
         // For multi dimensional data you could directly create them using alpaka::mem::buf::alloc<Type>(devHost, extent), which is not used here.
         // Instead we use ViewPlainPtr to wrap the data.
         using BufWrapper = alpaka::mem::view::ViewPlainPtr<
-            std::decay<decltype(devHost)>::type,
```
Comment (BenjaminW3) [inline test/integ/matMul/src/main.cpp]: This line was the real issue
