### PR TITLE
close #197: fix race condition

### LINKED ISSUE #197: Reference to already destroyed objects
I ported PIConGPU with the help of cupla to alpaka and get a deadlock that a kernel never finished ( the event after the kernel is not triggered).
I am not 100% sure if this is an alpaka bug but I think so.

If I use `::alpaka::stream::StreamCpuAsync` and `::alpaka::acc::AccCpuOmp2Threads<>` I can trigger a deadlock in the most runs. With `::alpaka::stream::StreamCpuSync` the deadlock is never triggered.

I think the problem is trigger by some code part like [this](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/ConcurrentExecPool.hpp#L362) where a functor is created and some arguments are [bind as reference](http://de.cppreference.com/w/cpp/utility/functional/bind). If the functor which is created with bind is passed to a thread than it can be that the (internal stored) references are not valid anymore.
This can be the case if an alpaka kernel is created in a local scope and passed to `::alpaka::stream::enqueue()`

```C++
{
 MyKernel kernel;
 auto dev( manager::Device<AccDev>::get().current() );
  ::alpaka::workdiv::WorkDivMembers<
    KernelDim,
    IdxType
  > workDiv(
      static_cast<IdxVec3>(gridSize),
      static_cast<IdxVec3>(blockSize),
      static_cast<IdxVec3>(elemPerThread)
  );
  auto const exec(::alpaka::exec::create<Acc>(workDiv, kernel, args...));
  ::alpaka::stream::enqueue(stream, exec);
} // kernel, workDiv and args are now destroyed and get invalid if references are used in a different thread which is already running
```

@BenjaminW3 Currently I can't find the place were we must definitely create a copy of the kernel and the given parameter to avoid that references are stored in [TaskPackages](https://github.com/ComputationalRadiationPhysics/alpaka/blob/develop/include/alpaka/core/ConcurrentExecPool.hpp#L107). If my description of the problem is not clear enough could you please call me by phone (at work). I need some help to locate the broken code part.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- avoid that references are given to threads
- guard `notify_one` to avoid race conditions
- close #197

This branch removes also some `forward<>()` to avoid that a thread get the functors and parameters by reference to temporary resources of an other tread.

This pull request is rebased against #211 to avoid that appveyor fiber test always fails.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
The result of the race condition was that a thread add new work to the queue of the worker thread and notify the worker. The worker missed the notify if the thread is not in the conditional waiting function. If the worker than enter the waiting and no new work is added to the queue the thread never wake up.

File: include/alpaka/core/ConcurrentExecPool.hpp [hunk 1]
```diff
@@ -73,7 +73,7 @@ namespace alpaka
                 {
                     std::lock_guard<std::mutex> lk(m_Mutex);
 
-                    std::queue<T>::push(std::forward<T>(t));
+                    std::queue<T>::push(t);
```
Comment (BenjaminW3) [inline include/alpaka/core/ConcurrentExecPool.hpp]: I am very sure that this forward is no problem but a real optimization.

File: include/alpaka/core/ConcurrentExecPool.hpp [hunk 2]
```diff
@@ -159,7 +159,7 @@ namespace alpaka
                 TaskPkg(
                     TFnObj && func) :
                         m_Promise(),
-                        m_FnObj(std::forward<TFnObj>(func))
+                        m_FnObj(func)
```
Comment (BenjaminW3) [inline include/alpaka/core/ConcurrentExecPool.hpp]: The same as above should be true here. Therefore we should use `typename std::remove_reference<TFnObj>::type m_FnObj;` as the member to allow only copies and moves as the current version (even without forward) allows to hold a reference.

File: include/alpaka/core/ConcurrentExecPool.hpp [hunk 3]
```diff
@@ -209,7 +209,7 @@ namespace alpaka
                 TaskPkg(
                     TFnObj && func) :
                         m_Promise(),
-                        m_FnObj(std::forward<TFnObj>(func))
```
Comment (BenjaminW3) [inline include/alpaka/core/ConcurrentExecPool.hpp]: Same here.

File: include/alpaka/core/ConcurrentExecPool.hpp [hunk 4]
```diff
@@ -589,6 +589,7 @@ namespace alpaka
 
                     auto future(pTaskPackage->m_Promise.get_future());
 
+                    std::lock_guard<TMutex> lock(m_mtxWakeup);
                     m_qTasks.push(std::move(upTaskPackage));
 
                     m_cvWakeup.notify_one();
```
Comment (BenjaminW3) [inline include/alpaka/core/ConcurrentExecPool.hpp]: Could you please add `{` and `}` around lines 592 to 595 to make it stand out better?

File: include/alpaka/core/ConcurrentExecPool.hpp (hunk 1 above)
Comment (psychocoderHPC) [inline include/alpaka/core/ConcurrentExecPool.hpp]: But `t` is a reference to a function local shared pointer of a thread different to the worker thread. Therefore it is not allowed to hold a reference.

File: include/alpaka/core/ConcurrentExecPool.hpp (hunk 2 above)
Comment (psychocoderHPC) [inline include/alpaka/core/ConcurrentExecPool.hpp]: Yes I will add this change to this pull request

File: include/alpaka/core/ConcurrentExecPool.hpp (hunk 4 above)
Comment (psychocoderHPC) [inline include/alpaka/core/ConcurrentExecPool.hpp]: ok

File: include/alpaka/core/ConcurrentExecPool.hpp (hunk 1 above)
Comment (BenjaminW3) [inline include/alpaka/core/ConcurrentExecPool.hpp]: No, because `push` is no template, `T && t` is no 'universal reference' (representing either `&` or `&&`) but is forced to be a rvalue reference (`&&`). This means that `t` can only ever be moved into the `push` function. This means that the caller will always give up his reference and will transfer the ownership to the `push` function which will then transfer it to the internal queue via `forward`. At the call side, this can be reognized by the `std::move(upTaskPackage)`. It will not compile without the `std::move`.

Comment (psychocoderHPC) [inline include/alpaka/core/ConcurrentExecPool.hpp]: OK thanks for clarifing

File: include/alpaka/core/ConcurrentExecPool.hpp (hunk 4 above)
Comment (psychocoderHPC) [inline include/alpaka/core/ConcurrentExecPool.hpp]: I add the last changes after the GTC2016.

**Comment by psychocoderHPC** [comment]
updated

**Comment by BenjaminW3** [comment]
Thanks!
